version: '3.6'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: it4409
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"