version: '3.6'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: it4409
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123

    ports:
      - "3336:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"